### ISSUE TITLE
Unable to install MercadoPagoSDK pod

### ISSUE THREAD

**Issue by frangeris** [proyecto26/react-native-mercado-pago-enterprise#1]
Hi guys, 

I've being trying to integrate mercadopago into an app, but I'm having some issues while installing, I've followed the setup instructions but when adding the pod it ask for github credentials to install a dependency (AndesUI)

![imagen](https://user-images.githubusercontent.com/811381/113446655-9d81af00-93ce-11eb-9cd5-0c9a525c8bcb.png)
 
I dont know how to continue as this is a dependency of mercadopago sdk, what could be the workaround? 

Thanks in advance :)

**Comment by jdnichollsc** [comment]
Hello Frangeris, nice to meet you!

Thanks for your support! If you want we can have a meeting to review that 🙂 Please schedule our meeting in this link https://calendly.com/jdnichollsc

Let me check the demo project to see if I can reproduce this issue.

Have a great Friday!

**Comment by frangeris** [comment]
Thank you @jdnichollsc, nice to meet you too :)

It shouldn't be an issue, I'm just installing from scratch in a project, I appreciate the disposition, but think that this could not be related to your bridge, due that I'm able to install the package correctly, but the issue comes up only when adding the dependency in pods, so `AndesUI` seems to be a private dependency from mercado pago team, not sure how to proceed : /

**Comment by jdnichollsc** [comment]
Can you attach your repo or Podfile config please? I can help you with that issue if you want 🙂

**Comment by frangeris** [comment]
Yea, sure, here's my Podfile


```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :disable_input_output_paths => true
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

target 'myapp' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'Firebase/Auth'
  pod 'FBSDKLoginKit'
  pod 'MercadoPagoSDK', :build_type => :dynamic_framework
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

```

It keeps asking for github credentials due `AndesUI` is private and required by `MercadoPagoSDK`

**Comment by jdnichollsc** [comment]
Eres de Argentina? Si quieres nos conectamos y lo revisamos juntos, te parece? 😁

**Comment by frangeris** [comment]
Si, debugeare un poco mas para no hacerte perder el tiempo, estoy probando la `example` app que trae de prueba, instala todos los pods correctamente, al parecer el problema soy yo, verifico mas en detalle y te dejo saber.

Te agradezco mucho, 

Gracias!

**Comment by jdnichollsc** [comment]
Dale, quedo pendiente! Realmente no tengo ningún problema de que lo revisemos juntos, por el contrario me gustaría colaborarte en lo que necesites, igualmente uso el mismo enlace que te pasé para dar mentorias totalmente gratis si te interesa ❤️

Un abrazo y feliz viernes! 👍

**Comment by frangeris** [comment]
Encontre el issue con la instalacion del pod, tuve que especificar la version `4.18.3` para `MercadoPagoSDK`, que condidencialmente es el ultimo release "public release", la razon de porque funciona en tu example es porque es la version que tienes en `Podfile.lock`.

A partir de esta version pasaron a ser "Release Private v4.19.0", tienes idea de porque sucede esto, porque ahora son privados? como se puede acceder a estos?

La version que se puede instalar es muy vieja, sabes si hay forma de soportar de alguna manera los ultimos releases?

EDIT: 
La ultima version publica es la `4.32.4`

**Comment by jdnichollsc** [comment]
Ohh interesante, aquí ando revisando, déjame te confirmo en un momento, gracias!

**Comment by frangeris** [comment]
PD: no estas usando el ultimo release publico... `4.32.4`

**Comment by jdnichollsc** [comment]
@frangeris sí aquí ando actualizando el repo, qué versión de React Native y Xcode estás usando? :)

**Comment by frangeris** [comment]
```
    "react": "16.13.1",
    "react-native": "0.63.4",
```
`Xcode Version 11.6 (11E708)`

**Comment by frangeris** [comment]
Nevermind, por alguna razon estaba usando una version de `AndesUI` vieja que estaba privada (`3.22.0`), desde el `Podfile.lock`, un simple `pod update` upgradeo la version a una no privada `AndesUI (3.27.4)`, con eso ya estaria resuelto el tema del pod.

Estare intentando usar la nueva version del SDK de mercado pago, te dejare saber si algo falla, 

Gracias de antemanos!

**Comment by jdnichollsc** [comment]
Gracias por dejarme saber, ando revisando unos issues de esas versiones con Flipper, me dió por actualizar Xcode y ahora tengo más errores que antes jaja

**Comment by jdnichollsc** [comment]
Acabo de subir los cambios al proyecto de ejemplo https://github.com/proyecto26/react-native-mercado-pago
Por otro lado el proyecto de ejemplo es un WIP, déjame saber si quisieras ver alguna otra funcionalidad, etc
Este es otro template que estoy haciendo con varios modos Offline: https://github.com/proyecto26/MyApp
Saludos y feliz fin de semana! <3

![image](https://user-images.githubusercontent.com/2154886/113469001-9929b600-940f-11eb-8274-e6b0b6f2b2ee.png)

**Comment by lualbergipe** [comment]
Hola Juan David como vas,  adquirí hoy el proyecto de mercado pago para react-native, lo estoy tratando de ejecutar peor no he podido, he seguido los pasos que describes en la documentación pero sin exito, cuando ejecuto el pod install me sale este error.

mi versión de react es: react-native: 0.62.2

<img width="1440" alt="Captura de Pantalla 2021-04-29 a la(s) 10 06 44 p  m" src="https://user-images.githubusercontent.com/32961849/116643710-47ede300-a937-11eb-9b6c-9e6836baa10d.png">

**Comment by jdnichollsc** [comment]
Hola @lualbergipe, gracias por dejarme saber, ya probaste instalando el plugin de Cocoapods como menciono en el README?

> gem install cocoapods-user-defined-build-types

Gracias por tu colaboración.
Saludos!

**Comment by lualbergipe** [comment]
cuando lo trato de instalar me sale esto:
<img width="1440" alt="Captura de Pantalla 2021-04-29 a la(s) 11 09 32 p  m" src="https://user-images.githubusercontent.com/32961849/116647419-188fa400-a940-11eb-8ce3-a30d21da57cc.png">
no se si estoy obviando alguna instalación posterior

**Comment by jdnichollsc** [comment]
@lualbergipe qué versión de MacOS tienes? Qué versión de Cocoapods? Podrías actualizar a la última versión?

Gracias por compartir!

**Comment by lualbergipe** [comment]
Mac OS Big sur version 11.2.1
cocoapods al parecer no esta instalado y trato de hacerlo con sudo gem install cocoapods y me sale exactamente el mismo error que relacione en el mensaje anterior, adicional actualice ruby para descartar la version del gem

**Comment by jdnichollsc** [comment]
Si quieres puedes agendar una reunión conmigo y te ayudo a revisar para configurar bien el ambiente 🙂 https://calendly.com/jdnichollsc

**Comment by jdnichollsc** [comment]
Hola! Recuerden que si tienen algún inconveniente me pueden contactar por Skype, Messenger, LinkedIn, etc con el usuario **jdnichollsc** para facilitar la comunicación 😃
