### ISSUE TITLE
Unable to resolve module "react-native-mercado-pago"

### ISSUE THREAD

**Issue by argos-pina** [proyecto26/react-native-mercado-pago-enterprise#3]
Estoy intentando usar la librería pero no la detecta react native (android)

![image](https://user-images.githubusercontent.com/84942264/126858929-18a7f89a-7783-49bc-ba78-ee17bf13a5ba.png)

Hice los pasos de instalación automática que vienen en la [documentación](https://github.com/proyecto26/react-native-mercado-pago-enterprise) pero no funcionó y tampoco con la instalación manual.

La carpeta de react-native-mercado-pago está en el mismo nivel que la de mi proyecto.

Estas son mis dependencias
`

    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@react-native-async-storage/async-storage": "^1.15.1",
    "@react-native-community/checkbox": "^0.5.7",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/auth": "^12.1.0",
    "@react-native-firebase/messaging": "^12.1.0",
    "@react-native-google-signin/google-signin": "^6.0.1",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "@reduxjs/toolkit": "^1.5.0",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-fast-image": "^8.3.4",
    "react-native-fbsdk-next": "^4.3.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-mercado-pago": "file:../react-native-mercado-pago",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-simple-toast": "^1.1.3",
    "react-native-size-matters": "^0.4.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^3.0.0",
    "react-native-uuid": "^2.0.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5"
`

**Comment by jdnichollsc** [comment]
Hola, gracias por soportar este proyecto! Intenta crear una carpeta **packages** o **libs** en tu proyecto, y luego ubica este plugin en esa carpeta, después de eso puedes actualizar el path desde el package.json y ejecutar el comando **npm install**.
Déjame saber si tienes alguna duda, igualmente podríamos tener una videollamada para resolver cualquier duda, saludos y nuevamente gracias por tu apoyo!

**Comment by argos-pina** [comment]
> Hola, gracias por soportar este proyecto! Intenta crear una carpeta **packages** o **libs** en tu proyecto, y luego ubica este plugin en esa carpeta, después de eso puedes actualizar el path desde el package.json y ejecutar el comando **npm install**.
> Déjame saber si tienes alguna duda, igualmente podríamos tener una videollamada para resolver cualquier duda, saludos y nuevamente gracias por tu apoyo!

Funciona! muchas gracias!

**Comment by jdnichollsc** [comment]
Genial, gracias por responder! ❤️
