### ISSUE TITLE
Disparar método de pago específico

### ISSUE THREAD

**Issue by krlol** [proyecto26/react-native-mercado-pago-enterprise#6]
Hola! Una pregunta, se puede disparar el método de pago que yo especifique¿

Por ejemplo si quiero que sea pago en tarjeta, directamente que aviente la opción de tarjeta o mande al usuario a dicho flujo, en lugar de que sea el usuario el que selecciona.

Disculpa que lo meta como issue pero no sabía donde más preguntar.

Saludos y gracias.

**Comment by jdnichollsc** [comment]
@krlol hola Karlo, espero que estés bien

Eso que indicas son opciones de la preferencia de pago, las cuales deben de ser especificadas en el momento que se crea la preferencia de pago (excluded_payment_methods).

Revisa la API para más información: https://www.mercadopago.com.co/developers/en/reference/preferences/_checkout_preferences/post

Si estás creando la preferencia desde tu Backend, para la muestra un botón desde la API de ejemplo: https://github.com/proyecto26/mercadopago-api/blob/main/src/services/payment.ts#L83

Déjame saber si tienes alguna otra duda al respecto.
